# Generated by Django 6.0.1 on 2026-01-17 06:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Depo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, verbose_name='Depo Adı')),
                ('adres', models.CharField(blank=True, max_length=200, verbose_name='Lokasyon / Adres')),
                ('is_sanal', models.BooleanField(default=False, verbose_name='Sanal / Tedarikçi Deposu mu?')),
            ],
            options={
                'verbose_name_plural': 'Depo Tanımları',
            },
        ),
        migrations.CreateModel(
            name='GiderKategorisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, verbose_name='Gider Kategorisi')),
            ],
            options={
                'verbose_name': 'Gider Tanımı',
                'verbose_name_plural': 'Gider Tanımları',
            },
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, verbose_name='Kategori Adı')),
            ],
            options={
                'verbose_name_plural': '1. İmalat Türleri',
            },
        ),
        migrations.CreateModel(
            name='Malzeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=200, verbose_name='Malzeme Adı (Örn: Ø14 Demir)')),
                ('kategori', models.CharField(choices=[('genel', 'Genel Malzeme'), ('hirdavat', 'Hırdavat / Nalburiye'), ('elektrik', 'Elektrik & Aydınlatma'), ('mekanik', 'Mekanik & Tesisat'), ('insaat', 'Kaba İnşaat (Çimento/Demir)'), ('boya', 'Boya & Kimyasal'), ('demirbas', 'Demirbaş / Ekipman')], default='genel', max_length=20, verbose_name='Malzeme Grubu')),
                ('marka', models.CharField(blank=True, max_length=100, verbose_name='Marka / Model')),
                ('birim', models.CharField(choices=[('adet', 'Adet'), ('m2', 'Metrekare (m²)'), ('m3', 'Metreküp (m³)'), ('kg', 'Kilogram (kg)'), ('ton', 'Ton'), ('mt', 'Metre (mt)'), ('adam_saat', 'Adam/Saat'), ('goturu', 'Götürü (Toplu)')], default='adet', max_length=20)),
                ('kdv_orani', models.IntegerField(choices=[(0, '%0'), (5, '%5'), (10, '%10'), (16, '%16'), (20, '%20')], default=20, verbose_name='Varsayılan KDV (%)')),
                ('kritik_stok', models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Kritik Stok Uyarı Limiti')),
                ('aciklama', models.TextField(blank=True, verbose_name='Teknik Özellikler / Notlar')),
            ],
            options={
                'verbose_name': '7. Envanter (Stok Durumu)',
                'verbose_name_plural': '7. Envanter (Stok Durumu)',
            },
        ),
        migrations.CreateModel(
            name='SatinAlma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siparis_tarihi', models.DateField(default=django.utils.timezone.now, verbose_name='Sipariş Tarihi')),
                ('teslimat_durumu', models.CharField(choices=[('bekliyor', '🔴 Bekliyor (Hiç Gelmedi)'), ('kismi', '🟠 Kısmi Teslimat (Eksik Var)'), ('tamamlandi', '🟢 Tamamlandı (Hepsi Geldi)')], default='bekliyor', max_length=20)),
                ('toplam_miktar', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Sipariş Edilen Toplam')),
                ('teslim_edilen', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Depoya Giren (Fiziksel)')),
                ('faturalanan_miktar', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Faturası Gelen (Finansal)')),
                ('fiili_odenen_tutar', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Şu Ana Kadar Ödenen')),
                ('aciklama', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '4. Satınalma & Siparişler',
                'verbose_name_plural': '4. Satınalma & Siparişler',
            },
        ),
        migrations.CreateModel(
            name='Tedarikci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_unvani', models.CharField(max_length=200, verbose_name='Firma Ünvanı')),
                ('yetkili_kisi', models.CharField(blank=True, max_length=100, verbose_name='Yetkili Kişi')),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('adres', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Tedarikçiler',
            },
        ),
        migrations.CreateModel(
            name='Harcama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aciklama', models.CharField(max_length=200, verbose_name='Harcama Açıklaması')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Tutar')),
                ('para_birimi', models.CharField(choices=[('TRY', 'Türk Lirası (₺)'), ('USD', 'Amerikan Doları ($)'), ('EUR', 'Euro (€)'), ('GBP', 'İngiliz Sterlini (£)')], default='TRY', max_length=3, verbose_name='Para Birimi')),
                ('kur_degeri', models.DecimalField(decimal_places=4, default=1.0, max_digits=10, verbose_name='İşlem Kuru')),
                ('tarih', models.DateField(default=django.utils.timezone.now, verbose_name='Harcama Tarihi')),
                ('dekont', models.FileField(blank=True, null=True, upload_to='harcamalar/', verbose_name='Dekont / Fiş')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harcamalar', to='core.giderkategorisi', verbose_name='Gider Türü')),
            ],
            options={
                'verbose_name': '5. Harcama (Gider)',
                'verbose_name_plural': '5. Harcamalar (Gider)',
                'ordering': ['-tarih'],
            },
        ),
        migrations.CreateModel(
            name='IsKalemi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=200, verbose_name='İş Kalemi Adı')),
                ('hedef_miktar', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Yaklaşık Metraj')),
                ('birim', models.CharField(choices=[('adet', 'Adet'), ('m2', 'Metrekare (m²)'), ('m3', 'Metreküp (m³)'), ('kg', 'Kilogram (kg)'), ('ton', 'Ton'), ('mt', 'Metre (mt)'), ('adam_saat', 'Adam/Saat'), ('goturu', 'Götürü (Toplu)')], default='adet', max_length=20)),
                ('kdv_orani', models.IntegerField(choices=[(0, '%0'), (5, '%5'), (10, '%10'), (16, '%16'), (20, '%20')], default=20, verbose_name='Varsayılan KDV (%)')),
                ('aciklama', models.TextField(blank=True, verbose_name='İş Tanımı / Teknik Şartname')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kalemler', to='core.kategori', verbose_name='Kategori')),
            ],
            options={
                'verbose_name_plural': '2. İş Kalemleri',
            },
        ),
        migrations.CreateModel(
            name='DepoTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Transfer Miktarı')),
                ('tarih', models.DateField(default=django.utils.timezone.now)),
                ('aciklama', models.CharField(blank=True, max_length=200, verbose_name='Transfer Notu (Plaka vb.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hedef_depo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giris_transferleri', to='core.depo', verbose_name='Hedef Depo (Nereye?)')),
                ('kaynak_depo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cikis_transferleri', to='core.depo', verbose_name='Kaynak Depo (Nereden?)')),
                ('malzeme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.malzeme', verbose_name='Taşınacak Malzeme')),
            ],
            options={
                'verbose_name': '8. Sevkiyat (Mal Kabul)',
                'verbose_name_plural': '8. Sevkiyat (Mal Kabul)',
            },
        ),
        migrations.CreateModel(
            name='MalzemeTalep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='İstenen Miktar')),
                ('oncelik', models.CharField(choices=[('normal', '🟢 Normal'), ('acil', '🔴 Acil'), ('cok_acil', '🔥 ÇOK ACİL (İş Durdu)')], default='normal', max_length=10, verbose_name='Aciliyet Durumu')),
                ('proje_yeri', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kullanılacak Yer')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('durum', models.CharField(choices=[('bekliyor', '⏳ Talep Açıldı (Onay Bekliyor)'), ('islemde', '🔍 Satınalma / Teklif Sürecinde'), ('onaylandi', '✅ Sipariş Verildi'), ('tamamlandi', '📦 Temin Edildi / Geldi'), ('red', '❌ Reddedildi / İptal')], default='bekliyor', max_length=20)),
                ('tarih', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Talep Tarihi')),
                ('onay_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Onaylanma Zamanı')),
                ('temin_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Temin/Teslim Zamanı')),
                ('is_kalemi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talepler', to='core.iskalemi', verbose_name='İş Kalemi (Hizmet/Taşeron)')),
                ('malzeme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talepler', to='core.malzeme', verbose_name='Malzeme (Satınalma)')),
                ('talep_eden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Talep Eden')),
            ],
            options={
                'verbose_name_plural': 'Malzeme ve Hizmet Talepleri',
                'ordering': ['-tarih'],
            },
        ),
        migrations.CreateModel(
            name='Hakedis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hakedis_no', models.PositiveIntegerField(default=1, verbose_name='Hakediş No')),
                ('tarih', models.DateField(default=django.utils.timezone.now, verbose_name='Hakediş Tarihi')),
                ('donem_baslangic', models.DateField(blank=True, null=True, verbose_name='Dönem Başı')),
                ('donem_bitis', models.DateField(blank=True, null=True, verbose_name='Dönem Sonu')),
                ('aciklama', models.TextField(blank=True, verbose_name='Yapılan İşin Açıklaması')),
                ('tamamlanma_orani', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Bu Dönem İlerleme (%)')),
                ('brut_tutar', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Hakediş Tutarı (KDV Hariç)')),
                ('kdv_orani', models.PositiveIntegerField(default=20, verbose_name='KDV (%)')),
                ('kdv_tutari', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='KDV Tutarı')),
                ('stopaj_orani', models.PositiveIntegerField(default=0, help_text='Genelde %3', verbose_name='Stopaj (%)')),
                ('stopaj_tutari', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Kesilen Stopaj')),
                ('teminat_orani', models.PositiveIntegerField(default=0, help_text='Genelde %5 veya %10', verbose_name='Teminat (%)')),
                ('teminat_tutari', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Kesilen Teminat')),
                ('avans_kesintisi', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Avans Kesintisi')),
                ('diger_kesintiler', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Malzeme/Ceza vb.')),
                ('odenecek_net_tutar', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Ödenecek Net Tutar')),
                ('fiili_odenen_tutar', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Şu Ana Kadar Ödenen')),
                ('onay_durumu', models.BooleanField(default=False, verbose_name='Onaylandı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('satinalma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hakedisler', to='core.satinalma', verbose_name='İlgili Sözleşme')),
            ],
            options={
                'verbose_name_plural': '6. Taşeron Hakedişleri',
                'ordering': ['-tarih'],
            },
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fatura_no', models.CharField(max_length=50, verbose_name='Fatura No')),
                ('tarih', models.DateField(default=django.utils.timezone.now, verbose_name='Fatura Tarihi')),
                ('miktar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fatura Edilen Miktar')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Fatura Tutarı (KDV Dahil)')),
                ('dosya', models.FileField(blank=True, null=True, upload_to='faturalar/', verbose_name='Fatura Görseli/PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('depo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.depo', verbose_name='Giriş Yapılacak Depo')),
                ('satinalma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturalar', to='core.satinalma', verbose_name='İlgili Sipariş')),
            ],
            options={
                'verbose_name': 'Alış Faturası',
                'verbose_name_plural': 'Alış Faturaları',
            },
        ),
        migrations.CreateModel(
            name='Odeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(default=django.utils.timezone.now, verbose_name='İşlem Tarihi')),
                ('odeme_turu', models.CharField(choices=[('nakit', 'Nakit'), ('havale', 'Havale / EFT'), ('cek', 'Çek')], default='nakit', max_length=10, verbose_name='Ödeme Yöntemi')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Ödenen Tutar')),
                ('para_birimi', models.CharField(choices=[('TRY', 'Türk Lirası (₺)'), ('USD', 'Amerikan Doları ($)'), ('EUR', 'Euro (€)'), ('GBP', 'İngiliz Sterlini (£)')], default='TRY', max_length=3, verbose_name='Para Birimi')),
                ('banka_adi', models.CharField(blank=True, max_length=100, verbose_name='Banka Adı')),
                ('cek_no', models.CharField(blank=True, max_length=50, verbose_name='Çek No / Dekont No')),
                ('vade_tarihi', models.DateField(blank=True, null=True, verbose_name='Çek Vadesi')),
                ('aciklama', models.CharField(blank=True, max_length=200, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bagli_hakedis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hakedis', verbose_name='İlgili Hakediş')),
                ('tedarikci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odemeler', to='core.tedarikci', verbose_name='Ödenen Firma')),
            ],
            options={
                'verbose_name': '7. Ödeme & Çek Çıkışı',
                'verbose_name_plural': '7. Ödeme & Çek Çıkışı',
                'ordering': ['-tarih'],
            },
        ),
        migrations.CreateModel(
            name='DepoHareket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(default=django.utils.timezone.now)),
                ('islem_turu', models.CharField(choices=[('giris', '📥 Depo Girişi (Satınalma/Transfer)'), ('cikis', '📤 Depo Çıkışı (Kullanım/Transfer)'), ('iade', '↩️ İade / Red (Kusurlu Mal)')], max_length=10)),
                ('miktar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miktar')),
                ('irsaliye_no', models.CharField(blank=True, max_length=50, verbose_name='İrsaliye No')),
                ('aciklama', models.CharField(blank=True, max_length=300, verbose_name='Açıklama / Kullanılan Yer')),
                ('iade_sebebi', models.CharField(blank=True, max_length=200, verbose_name='Red Sebebi')),
                ('iade_aksiyonu', models.CharField(choices=[('yok', '-'), ('degisim', '🔄 Yenisi Gelecek (Borç Düşme)'), ('iptal', '⛔ İptal Et / Faturadan Düş (Borç Düş)')], default='yok', max_length=20, verbose_name='İade Sonucu')),
                ('kanit_gorseli', models.ImageField(blank=True, null=True, upload_to='depo_kanit/', verbose_name='Hasar/Kanıt Fotoğrafı')),
                ('depo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.depo', verbose_name='İlgili Depo')),
                ('malzeme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hareketler', to='core.malzeme')),
                ('siparis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depo_hareketleri', to='core.satinalma', verbose_name='Bağlı Sipariş')),
                ('tedarikci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tedarikci', verbose_name='Tedarikçi (Giriş ise)')),
            ],
            options={
                'verbose_name': 'Hareket Geçmişi (Log)',
                'verbose_name_plural': 'Hareket Geçmişi (Log)',
            },
        ),
        migrations.CreateModel(
            name='Teklif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Teklif Miktarı')),
                ('birim_fiyat', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Birim Fiyat (KDV Hariç)')),
                ('para_birimi', models.CharField(choices=[('TRY', 'Türk Lirası (₺)'), ('USD', 'Amerikan Doları ($)'), ('EUR', 'Euro (€)'), ('GBP', 'İngiliz Sterlini (£)')], default='TRY', max_length=3)),
                ('kur_degeri', models.DecimalField(decimal_places=4, default=1.0, max_digits=10, verbose_name='İşlem Kuru')),
                ('kdv_dahil_mi', models.BooleanField(default=False, verbose_name='Bu fiyata KDV Dahil mi?')),
                ('kdv_orani', models.IntegerField(choices=[(0, '%0'), (5, '%5'), (10, '%10'), (16, '%16'), (20, '%20')], default=20, verbose_name='KDV Oranı')),
                ('teklif_dosyasi', models.FileField(blank=True, null=True, upload_to='teklifler/', verbose_name='Teklif PDF/Resim')),
                ('durum', models.CharField(choices=[('beklemede', '⏳ İncelemede'), ('onaylandi', '✅ Onaylandı (Sipariş)'), ('reddedildi', '❌ Reddedildi')], default='beklemede', max_length=20)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('is_kalemi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teklifler', to='core.iskalemi', verbose_name='İş Kalemi (Taşeronluk)')),
                ('malzeme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teklifler', to='core.malzeme', verbose_name='Malzeme (Satınalma)')),
                ('talep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teklifler', to='core.malzemetalep', verbose_name='İlgili Talep')),
                ('tedarikci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teklifler', to='core.tedarikci')),
            ],
            options={
                'verbose_name': '3. Teklifler (Fiyat Toplama)',
                'verbose_name_plural': '3. Teklifler (Fiyat Toplama)',
            },
        ),
        migrations.AddField(
            model_name='satinalma',
            name='teklif',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='satinalma_donusumu', to='core.teklif', verbose_name='İlgili Teklif'),
        ),
    ]
