# Generated by Django 6.0.1 on 2026-01-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='odenen_tutar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Ödenen Tutar'),
        ),
    ]
