# Generated by Django 6.0.1 on 2026-01-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='odeme',
            name='is_cek_odendi',
            field=models.BooleanField(default=False, verbose_name='Çek Tahsil Edildi mi?'),
        ),
    ]
