# Generated by Django 6.0.1 on 2026-01-17 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depotransfer',
            name='bagli_siparis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferler', to='core.satinalma', verbose_name='Bağlı Sipariş'),
        ),
    ]
