# Generated by Django 6.0.1 on 2026-01-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_depotransfer_bagli_siparis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iskalemi',
            name='kdv_orani',
            field=models.IntegerField(choices=[(-1, 'KDV Muaf / Özel Matrah'), (0, '%0'), (5, '%5'), (10, '%10'), (16, '%16'), (20, '%20')], default=20, verbose_name='Varsayılan KDV (%)'),
        ),
        migrations.AlterField(
            model_name='malzeme',
            name='kdv_orani',
            field=models.IntegerField(choices=[(-1, 'KDV Muaf / Özel Matrah'), (0, '%0'), (5, '%5'), (10, '%10'), (16, '%16'), (20, '%20')], default=20, verbose_name='Varsayılan KDV (%)'),
        ),
        migrations.AlterField(
            model_name='teklif',
            name='kdv_orani',
            field=models.IntegerField(choices=[(-1, 'KDV Muaf / Özel Matrah'), (0, '%0'), (5, '%5'), (10, '%10'), (16, '%16'), (20, '%20')], default=20, verbose_name='KDV Oranı'),
        ),
    ]
