# Generated by Django 6.0.1 on 2026-01-21 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fatura_odenen_tutar'),
    ]

    operations = [
        migrations.AddField(
            model_name='odeme',
            name='fatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odemeler', to='core.fatura', verbose_name='İlgili Fatura'),
        ),
    ]
