# Generated by Django 6.0.1 on 2026-01-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_iskalemi_kdv_orani_alter_malzeme_kdv_orani_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depo',
            name='is_kullanim_yeri',
            field=models.BooleanField(default=False, help_text="İşaretlenirse bu depoya transfer edilen mallar 'stoktan düşer' (tüketilmiş sayılır).", verbose_name='Kullanım / Sarf Yeri mi?'),
        ),
    ]
