# Generated by Django 6.0.1 on 2026-01-22 11:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_odeme_fatura'),
    ]

    operations = [
        migrations.CreateModel(
            name='OdemeDagitim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Dağıtılan Tutar (TL)')),
                ('tarih', models.DateField(default=django.utils.timezone.now, verbose_name='Mahsup Tarihi')),
                ('aciklama', models.CharField(blank=True, default='', max_length=200, verbose_name='Not')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dagitimlar', to='core.fatura', verbose_name='Fatura')),
                ('odeme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dagitimlar', to='core.odeme', verbose_name='Ödeme')),
            ],
            options={
                'verbose_name': 'Ödeme Dağıtım (Mahsup)',
                'verbose_name_plural': 'Ödeme Dağıtımları (Mahsup)',
                'ordering': ['-tarih', '-id'],
                'constraints': [models.UniqueConstraint(fields=('odeme', 'fatura', 'tarih'), name='uniq_odeme_fatura_tarih')],
            },
        ),
    ]
