# Generated by Django 6.0.1 on 2026-01-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_depo_is_kullanim_yeri'),
    ]

    operations = [
        migrations.AddField(
            model_name='depo',
            name='depo_tipi',
            field=models.CharField(choices=[('WAREHOUSE', 'Fiziksel Depo'), ('SITE', 'Şantiye Deposu'), ('VENDOR', 'Tedarikçi Deposu (Vendor Location)'), ('CONSUMPTION', 'Kullanım / Sarf Yeri')], default='WAREHOUSE', max_length=20, verbose_name='Depo Tipi'),
        ),
        migrations.AddField(
            model_name='depohareket',
            name='ref_direction',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Referans Yönü (IN/OUT)'),
        ),
        migrations.AddField(
            model_name='depohareket',
            name='ref_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Referans ID'),
        ),
        migrations.AddField(
            model_name='depohareket',
            name='ref_type',
            field=models.CharField(blank=True, choices=[('TRANSFER', 'Depo Transfer'), ('FATURA', 'Fatura'), ('MANUEL', 'Manuel'), ('IADE', 'İade')], max_length=20, null=True, verbose_name='Referans Tipi'),
        ),
        migrations.AlterField(
            model_name='depo',
            name='is_kullanim_yeri',
            field=models.BooleanField(default=False, verbose_name='Kullanım / Sarf Yeri mi?'),
        ),
        migrations.AlterField(
            model_name='hakedis',
            name='kdv_orani',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='KDV (%)'),
        ),
        migrations.AlterField(
            model_name='hakedis',
            name='stopaj_orani',
            field=models.PositiveIntegerField(default=0, verbose_name='Stopaj (%)'),
        ),
        migrations.AlterField(
            model_name='hakedis',
            name='teminat_orani',
            field=models.PositiveIntegerField(default=0, verbose_name='Teminat (%)'),
        ),
        migrations.AddConstraint(
            model_name='depohareket',
            constraint=models.UniqueConstraint(fields=('ref_type', 'ref_id', 'ref_direction', 'malzeme', 'depo'), name='uniq_depo_hareket_ref'),
        ),
    ]
