# Generated by Django 6.0.1 on 2026-01-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_odemedagitim'),
    ]

    operations = [
        migrations.AddField(
            model_name='depo',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Aktif mi?'),
        ),
        migrations.AddField(
            model_name='iskalemi',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Aktif mi?'),
        ),
        migrations.AddField(
            model_name='kategori',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Aktif mi?'),
        ),
        migrations.AddField(
            model_name='malzeme',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Aktif mi?'),
        ),
        migrations.AddField(
            model_name='tedarikci',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Aktif mi?'),
        ),
    ]
