# Generated by Django 6.0.1 on 2026-01-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_depo_is_active_iskalemi_is_active_kategori_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='giderkategorisi',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif mi?'),
        ),
    ]
