# Generated by Django 6.0.1 on 2026-01-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_giderkategorisi_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturakalem',
            name='kdv_dahil_mi',
            field=models.BooleanField(default=False, verbose_name='Fiyat KDV Dahil mi?'),
        ),
        migrations.AlterField(
            model_name='faturakalem',
            name='fiyat',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='Birim Fiyat'),
        ),
    ]
