# Generated by Django 6.0.1 on 2026-01-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_faturakalem_kdv_dahil_mi_alter_faturakalem_fiyat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faturakalem',
            name='kdv_dahil_mi',
            field=models.BooleanField(default=False, verbose_name='Bu fiyat KDV dahil mi?'),
        ),
    ]
